# Generated by Django 5.0.14 on 2026-09-22 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='teams.team'),
        ),
        migrations.AddField(
            model_name='parentplayerlink',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='accounts.player'),
        ),
        migrations.AddField(
            model_name='parentinvite',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='accounts.player'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.userrole'),
        ),
        migrations.AddConstraint(
            model_name='parentplayerlink',
            constraint=models.UniqueConstraint(condition=models.Q(('removed_at__isnull', True)), fields=('parent', 'player'), name='unique_active_parent_player_link'),
        ),
    ]
