# Generated by Django 5.0.14 on 2026-09-24 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentinvite',
            options={'verbose_name': 'Parent Invite', 'verbose_name_plural': 'Parent Invites'},
        ),
        migrations.AlterModelOptions(
            name='parentplayerlink',
            options={'verbose_name': 'Parent-Player Link', 'verbose_name_plural': 'Parent-Player Links'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'User Role', 'verbose_name_plural': 'User Roles'},
        ),
    ]
