# Generated by Django 5.0.14 on 2026-09-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_parentinvite_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentinvite',
            name='emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentinvite',
            name='invitee_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
