# Generated by Django 5.0.14 on 2026-09-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_options_user_unique_lower_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='is_public_profile',
            field=models.BooleanField(default=False, help_text="Whether this player's public-tier info (name, photo, jersey number, position, team) is visible on the public site. Off by default -- the parent (or admin) opts in."),
        ),
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='player_photos/'),
        ),
    ]
