# Generated by Django 5.0.14 on 2026-09-28 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_player_description_player_is_public_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='player_gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='accounts.player')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Player Gallery Photo',
                'verbose_name_plural': 'Player Gallery Photos',
                'ordering': ['-created_at'],
            },
        ),
    ]
