# Generated by Django 5.0.14 on 2026-09-28 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_player_gallery_photo'),
        ('teams', '0009_team_deleted_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_deleted_placeholder': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='teams.team'),
        ),
    ]
