# Generated by Django 5.0.14 on 2026-09-28 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_player_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentplayerlink',
            options={'ordering': ['player__last_name', 'player__first_name', 'parent__last_name'], 'verbose_name': 'Parent-Player Link', 'verbose_name_plural': 'Parent-Player Links'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name', 'email']},
        ),
    ]
