# Generated by Django 5.0.14 on 2026-09-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_parentplayerlink_options_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentinvite',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
