# Generated by Django 5.0.14 on 2026-09-29 06:37

from django.db import migrations, models


def set_initial_primaries(apps, schema_editor):
    """Each kid's longest-linked active adult becomes the primary parent."""
    ParentPlayerLink = apps.get_model("accounts", "ParentPlayerLink")
    seen = set()
    for link in ParentPlayerLink.objects.filter(removed_at__isnull=True).order_by(
        "player_id", "created_at", "pk"
    ):
        if link.player_id not in seen:
            seen.add(link.player_id)
            ParentPlayerLink.objects.filter(pk=link.pk).update(is_primary=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_parentinvite_cancelled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentplayerlink',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='The primary parent gets automated emails about this player, like overdue payment reminders. Exactly one active link per player is primary; ticking this moves it here.'),
        ),
        migrations.RunPython(set_initial_primaries, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='parentplayerlink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('removed_at__isnull', True)), fields=('player',), name='one_primary_parent_per_player'),
        ),
    ]
