# Generated by Django 5.0.14 on 2026-09-29 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_alter_fee_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_to_email', models.EmailField(max_length=254)),
                ('balance_at_send', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='fees.fee')),
                ('sent_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Overdue Fee Reminder',
                'verbose_name_plural': 'Overdue Fee Reminders',
                'ordering': ['-sent_at'],
            },
        ),
    ]
