# Generated by Django 5.0.14 on 2026-09-29 06:49

from django.db import migrations, models
from django.db.models import DecimalField, Sum, Value
from django.db.models.functions import Coalesce
from django.utils import timezone


def mark_existing_overdue(apps, schema_editor):
    """
    Gus shouldn't email balances that were already overdue before he
    started (user's choice, 2026-09-29): record every fee that's overdue
    right now, with a balance left, as reminded-but-not-sent. Runs at
    deploy time, so "right now" is whenever this reaches each database.
    """
    Fee = apps.get_model("fees", "Fee")
    FeeReminder = apps.get_model("fees", "FeeReminder")
    today = timezone.localdate()
    fees = (
        Fee.objects.filter(
            player__isnull=False,
            due_date__lt=today,
            reminder__isnull=True,
        )
        .annotate(
            paid=Coalesce(
                Sum("payments__amount"),
                Value(0),
                output_field=DecimalField(max_digits=10, decimal_places=2),
            )
        )
    )
    FeeReminder.objects.bulk_create(
        FeeReminder(fee=fee, balance_at_send=fee.amount_due - fee.paid, was_sent=False)
        for fee in fees
        if fee.amount_due - fee.paid > 0
    )


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_feereminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='feereminder',
            name='was_sent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='feereminder',
            name='sent_to_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.RunPython(mark_existing_overdue, migrations.RunPython.noop),
    ]
