# Generated by Django 5.0.14 on 2026-09-28 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('teams', '0009_team_deleted_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='team',
            field=models.ForeignKey(limit_choices_to={'is_deleted_placeholder': False}, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='teams.team'),
        ),
    ]
