# Generated by Django 5.0.14 on 2026-09-30 00:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_event_team'),
        ('teams', '0013_team_gamechanger_feed_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='feed_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='source',
            field=models.CharField(choices=[('manual', 'Added on the website'), ('gamechanger', 'Synced from GameChanger')], default='manual', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('team', 'external_id'), name='unique_external_event_per_team'),
        ),
    ]
