# Generated by Django 5.0.14 on 2026-09-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_event_external_id_event_feed_status_event_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('practice', 'Practice'), ('tournament', 'Tournament'), ('event', 'Event')], max_length=20),
        ),
    ]
