# Generated by Django 5.0.14 on 2026-09-22 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TryoutSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('positions', models.CharField(blank=True, max_length=100)),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('previous_team', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('parent_name', models.CharField(max_length=150)),
                ('parent_phone', models.CharField(max_length=30)),
                ('parent_email', models.EmailField(max_length=254)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('tryout_year', models.PositiveIntegerField(editable=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('attended', 'Attended')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TryoutYearSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_month', models.PositiveSmallIntegerField(default=9)),
                ('cutoff_day', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TryoutStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('attended', 'Attended')], max_length=20)),
                ('new_status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('attended', 'Attended')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='tryouts.tryoutsignup')),
            ],
        ),
    ]
