# Generated by Django 5.0.14 on 2026-09-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryouts', '0003_split_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryoutyearsettings',
            name='next_tryout_date',
            field=models.DateField(blank=True, help_text='Drives the public home page banner -- shown when this date is within 30 days.', null=True),
        ),
    ]
