# Generated by Django 5.0.14 on 2026-09-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryouts', '0004_tryoutyearsettings_next_tryout_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tryoutsignup',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Try-Out Sign-Up', 'verbose_name_plural': 'Try-Out Sign-Ups'},
        ),
        migrations.AlterModelOptions(
            name='tryoutstatuschange',
            options={'verbose_name': 'Try-Out Status Change', 'verbose_name_plural': 'Try-Out Status Changes'},
        ),
        migrations.AlterModelOptions(
            name='tryoutyearsettings',
            options={'verbose_name': 'Try-Out Year Settings', 'verbose_name_plural': 'Try-Out Year Settings'},
        ),
        migrations.AlterField(
            model_name='tryoutsignupposition',
            name='position',
            field=models.CharField(choices=[('LP', 'LH Pitcher'), ('RP', 'RH Pitcher'), ('C', 'Catcher'), ('B1', 'First Base'), ('B2', 'Second Base'), ('B3', 'Third Base'), ('SS', 'Shortstop'), ('LF', 'Left Field'), ('CF', 'Center Field'), ('RF', 'Right Field')], max_length=5),
        ),
    ]
