# Generated by Django 5.0.14 on 2026-09-24 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryouts', '0006_tryoutsignup_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tryoutsignup',
            name='coach_decision',
            field=models.CharField(choices=[('undecided', 'Undecided'), ('invite', 'Invite'), ('maybe', 'Maybe'), ('not_selected', 'Not Selected')], default='undecided', max_length=20),
        ),
        migrations.CreateModel(
            name='TryoutDecisionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_decision', models.CharField(choices=[('undecided', 'Undecided'), ('invite', 'Invite'), ('maybe', 'Maybe'), ('not_selected', 'Not Selected')], max_length=20)),
                ('new_decision', models.CharField(choices=[('undecided', 'Undecided'), ('invite', 'Invite'), ('maybe', 'Maybe'), ('not_selected', 'Not Selected')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_changes', to='tryouts.tryoutsignup')),
            ],
            options={
                'verbose_name': 'Try-Out Decision Change',
                'verbose_name_plural': 'Try-Out Decision Changes',
            },
        ),
    ]
