# Generated by Django 5.0.14 on 2026-09-24 23:23

import apps.tryouts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryouts', '0007_tryoutsignup_coach_decision_tryoutdecisionchange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tryoutsignup',
            name='family_response',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='TryoutResponseInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=apps.tryouts.models._default_response_expiry)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_invites', to='tryouts.tryoutsignup')),
            ],
            options={
                'verbose_name': 'Try-Out Response Invite',
                'verbose_name_plural': 'Try-Out Response Invites',
            },
        ),
    ]
