# Generated by Django 5.0.14 on 2026-09-24 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_parentinvite_options_and_more'),
        ('tryouts', '0008_tryoutsignup_family_response_tryoutresponseinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tryoutsignup',
            name='promoted_player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tryout_signup', to='accounts.player'),
        ),
        migrations.AddField(
            model_name='tryoutsignup',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
