# Generated by Django 5.0.14 on 2026-09-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryouts', '0009_tryoutsignup_promoted_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryoutresponseinvite',
            name='emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
