# Generated by Django 5.0.14 on 2026-09-25 03:16

from django.db import migrations, models


def convert_maybe_to_undecided(apps, schema_editor):
    # Belt-and-suspenders: as of this migration no signup has ever been set
    # to "maybe" (checked both local and the deployed DB), but this covers
    # the narrow window between writing this migration and it actually
    # deploying, during which the still-running old code could still set one.
    TryoutSignup = apps.get_model("tryouts", "TryoutSignup")
    TryoutSignup.objects.filter(coach_decision="maybe").update(coach_decision="undecided")


class Migration(migrations.Migration):

    dependencies = [
        ('tryouts', '0010_tryoutresponseinvite_emailed_at'),
    ]

    operations = [
        migrations.RunPython(convert_maybe_to_undecided, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tryoutdecisionchange',
            name='new_decision',
            field=models.CharField(choices=[('undecided', 'Undecided'), ('invite', 'Invite'), ('not_selected', 'Not Selected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tryoutdecisionchange',
            name='old_decision',
            field=models.CharField(choices=[('undecided', 'Undecided'), ('invite', 'Invite'), ('not_selected', 'Not Selected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tryoutsignup',
            name='coach_decision',
            field=models.CharField(choices=[('undecided', 'Undecided'), ('invite', 'Invite'), ('not_selected', 'Not Selected')], default='undecided', max_length=20),
        ),
    ]
