# Generated by Django 5.0.14 on 2026-09-25 04:22

from django.db import migrations, models


def copy_emailed_at_to_signup(apps, schema_editor):
    # Preserve any already-sent state (old admin-driven flow) onto the new
    # signup-level field before the old one is dropped, rather than
    # silently losing which signups had already been emailed.
    TryoutResponseInvite = apps.get_model("tryouts", "TryoutResponseInvite")
    for invite in TryoutResponseInvite.objects.exclude(emailed_at=None).order_by("emailed_at"):
        signup = invite.signup
        if not signup.decision_emailed_at:
            signup.decision_emailed_at = invite.emailed_at
            signup.save(update_fields=["decision_emailed_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('tryouts', '0011_alter_tryoutdecisionchange_new_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryoutsignup',
            name='decision_emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(copy_emailed_at_to_signup, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='tryoutresponseinvite',
            name='emailed_at',
        ),
    ]
