# Generated by Django 5.0.14 on 2026-09-27 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryouts', '0012_remove_tryoutresponseinvite_emailed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TryoutPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_type', models.CharField(choices=[('initial', 'Initial Tryouts'), ('supplemental', 'Supplemental / Make-Up Tryouts')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='tryout_posters/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this poster currently shows on the home page.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first, on the home page and in this list.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Try-Out Poster',
                'verbose_name_plural': 'Try-Out Posters',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
