# Generated by Django 5.0.14 on 2026-09-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryouts', '0013_tryoutposter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tryoutposter',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this poster currently shows on the home page. Only one poster can be active at a time, and the try-out sign-up form is closed unless one is.'),
        ),
    ]
