# Generated by Django 5.0.14 on 2026-09-28 22:47

import apps.teams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_team_deleted_placeholder'),
        ('tryouts', '0014_tryoutposter_single_active_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tryoutsignup',
            name='team',
            field=models.ForeignKey(on_delete=models.SET(apps.teams.models.get_deleted_team), related_name='tryout_signups', to='teams.team'),
        ),
    ]
