# Generated by Django 5.0.14 on 2026-09-28 23:14

import apps.teams.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_team_deleted_placeholder'),
        ('tryouts', '0015_alter_tryoutsignup_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TryoutMassEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(blank=True, choices=[('undecided', 'Undecided'), ('invite', 'Invite'), ('not_selected', 'Not Selected')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('recipients', models.JSONField(default=list)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=models.SET(apps.teams.models.get_deleted_team), related_name='+', to='teams.team')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
