# Generated by Django 5.0.14 on 2026-09-28 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tryouts', '0016_tryoutmassemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tryoutsignup',
            options={'ordering': ['player_last_name', 'player_first_name'], 'verbose_name': 'Try-Out Sign-Up', 'verbose_name_plural': 'Try-Out Sign-Ups'},
        ),
    ]
