# Generated by Django 5.0.14 on 2026-09-29 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_parentinvite_cancelled_at'),
        ('tryouts', '0017_alter_tryoutsignup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tryoutsignup',
            name='promoted_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tryout_signups', to='accounts.player'),
        ),
    ]
