# Generated by Django 5.0.14 on 2026-09-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryouts', '0018_promoted_player_foreignkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tryoutsignup',
            name='status',
        ),
        migrations.AlterField(
            model_name='tryoutdecisionchange',
            name='new_decision',
            field=models.CharField(choices=[('undecided', 'Undecided'), ('invite', 'Invite'), ('not_selected', 'Not Selected'), ('unattended', 'Unattended')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tryoutdecisionchange',
            name='old_decision',
            field=models.CharField(choices=[('undecided', 'Undecided'), ('invite', 'Invite'), ('not_selected', 'Not Selected'), ('unattended', 'Unattended')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tryoutmassemail',
            name='decision',
            field=models.CharField(blank=True, choices=[('undecided', 'Undecided'), ('invite', 'Invite'), ('not_selected', 'Not Selected'), ('unattended', 'Unattended')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tryoutsignup',
            name='coach_decision',
            field=models.CharField(choices=[('undecided', 'Undecided'), ('invite', 'Invite'), ('not_selected', 'Not Selected'), ('unattended', 'Unattended')], default='undecided', max_length=20),
        ),
        migrations.DeleteModel(
            name='TryoutStatusChange',
        ),
    ]
