# Generated by Django 5.0.14 on 2026-09-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryouts', '0019_remove_tryout_status_add_unattended'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryoutmassemail',
            name='audience',
            field=models.CharField(choices=[('tryouts', 'Try-out families'), ('roster', 'Team families')], default='tryouts', max_length=10),
        ),
    ]
