# Generated by Django 5.0.14 on 2026-09-22 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=50)),
                ('season_year', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-season_year', 'division'],
            },
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_text', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='coach_photos/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('coach', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'First base'), ('2B', 'Second base'), ('3B', 'Third base'), ('SS', 'Shortstop'), ('OF', 'Outfield')], max_length=5)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='accounts.player')),
            ],
        ),
        migrations.CreateModel(
            name='TeamCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('head', 'Head coach'), ('assistant', 'Assistant coach')], max_length=20)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_assignments', to='teams.team')),
            ],
        ),
        migrations.AddConstraint(
            model_name='playerposition',
            constraint=models.UniqueConstraint(fields=('player', 'position'), name='unique_player_position'),
        ),
        migrations.AddConstraint(
            model_name='teamcoach',
            constraint=models.UniqueConstraint(fields=('team', 'coach'), name='unique_team_coach'),
        ),
    ]
