# Generated by Django 5.0.14 on 2026-09-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerposition',
            name='position',
            field=models.CharField(choices=[('LP', 'Left-handed pitcher'), ('RP', 'Right-handed pitcher'), ('C', 'Catcher'), ('B1', 'First baseman'), ('B2', 'Second baseman'), ('B3', 'Third baseman'), ('SS', 'Shortstop'), ('LF', 'Left fielder'), ('CF', 'Center fielder'), ('RF', 'Right fielder')], max_length=5),
        ),
    ]
