# Generated by Django 5.0.14 on 2026-09-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_canonical_position_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachprofile',
            options={'verbose_name': 'Coach Profile', 'verbose_name_plural': 'Coach Profiles'},
        ),
        migrations.AlterField(
            model_name='playerposition',
            name='position',
            field=models.CharField(choices=[('LP', 'LH Pitcher'), ('RP', 'RH Pitcher'), ('C', 'Catcher'), ('B1', 'First Base'), ('B2', 'Second Base'), ('B3', 'Third Base'), ('SS', 'Shortstop'), ('LF', 'Left Field'), ('CF', 'Center Field'), ('RF', 'Right Field')], max_length=5),
        ),
    ]
