# Generated by Django 5.0.14 on 2026-09-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_coachprofile_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('name', 'season_year'), name='unique_team_name_per_season'),
        ),
    ]
