# Generated by Django 5.0.14 on 2026-09-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_unique_team_name_per_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='accepting_tryouts',
            field=models.BooleanField(default=False, help_text='Whether this team appears as a choice on the public try-out sign-up form.'),
        ),
        migrations.AddField(
            model_name='team',
            name='is_public',
            field=models.BooleanField(default=True, help_text="Whether this team shows up anywhere on the public site (Teams index/detail, Coaches, public Schedule). A team pre-created for an upcoming season should start unpublished until its roster is finalized and it's ready to be revealed."),
        ),
    ]
