# Generated by Django 5.0.14 on 2026-09-25 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_team_decisions_finalized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='decisions_finalized',
            field=models.BooleanField(default=False, help_text="Locks in this team's try-out decisions for reveal. Only flip this once every signup for this team has a final coach decision (not Undecided)."),
        ),
    ]
