# Generated by Django 5.0.14 on 2026-09-25 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_alter_team_decisions_finalized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='decisions_finalized',
        ),
    ]
