# Generated by Django 5.0.14 on 2026-09-28 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_remove_team_decisions_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_deleted_placeholder',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='teamcoach',
            name='team',
            field=models.ForeignKey(limit_choices_to={'is_deleted_placeholder': False}, on_delete=django.db.models.deletion.CASCADE, related_name='coach_assignments', to='teams.team'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted_placeholder', True)), fields=('is_deleted_placeholder',), name='single_deleted_team_placeholder'),
        ),
    ]
