# Generated by Django 5.0.14 on 2026-09-28 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_team_deleted_placeholder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachprofile',
            options={'ordering': ['coach__last_name', 'coach__first_name'], 'verbose_name': 'Coach Profile', 'verbose_name_plural': 'Coach Profiles'},
        ),
        migrations.AlterModelOptions(
            name='teamcoach',
            options={'ordering': ['coach__last_name', 'coach__first_name']},
        ),
    ]
