# Generated by Django 5.0.14 on 2026-09-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_alter_coachprofile_options_alter_teamcoach_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='list_first',
            field=models.BooleanField(default=False, help_text='Show this coach at the top of the public Coaches page.'),
        ),
    ]
