# Generated by Django 5.0.14 on 2026-09-29 01:52

from django.db import migrations


def pin_tom_nguyen(apps, schema_editor):
    """
    One-time data fix: the club owner (Tom Nguyen) goes at the top of the
    Coaches page. Afterwards list_first is managed in Django admin; this
    is a no-op on a database without him.
    """
    CoachProfile = apps.get_model("teams", "CoachProfile")
    CoachProfile.objects.filter(
        coach__first_name__iexact="Tom", coach__last_name__iexact="Nguyen"
    ).update(list_first=True)


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_coachprofile_list_first'),
    ]

    operations = [
        migrations.RunPython(pin_tom_nguyen, migrations.RunPython.noop),
    ]
