# Generated by Django 5.0.14 on 2026-09-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_pin_tom_nguyen'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='gamechanger_feed_url',
            field=models.CharField(blank=True, help_text='Paste the team\'s GameChanger "Copy calendar link" here to sync its schedule (python manage.py sync_gamechanger). Leave blank to turn syncing off.', max_length=500, verbose_name='GameChanger calendar link'),
        ),
        migrations.AddField(
            model_name='team',
            name='gamechanger_last_synced_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
